import {
    ARC_TESTNET_CHAIN_ID as CONTRACT_ARC_TESTNET_CHAIN_ID,
    PREMIUM_PAYMENT_RECIPIENT_ADDRESS,
    SUBSCRIPT_ROUTER_ADDRESS,
    USDC_NATIVE_GAS_ADDRESS
} from "@/lib/contracts/constants";

export const ARC_TESTNET_CHAIN_ID = CONTRACT_ARC_TESTNET_CHAIN_ID;
export const USDC_ADDRESS = USDC_NATIVE_GAS_ADDRESS;
export const ROUTER_ADDRESS = SUBSCRIPT_ROUTER_ADDRESS;
export const TREASURY_ADDRESS = PREMIUM_PAYMENT_RECIPIENT_ADDRESS;
export const PREMIUM_PRICE = 10000000;
