"use client";

import React from "react";
import * as P from "@phosphor-icons/react";

export type LucideIcon = React.ComponentType<P.IconProps>;

const wrap = (IconComponent: React.ComponentType<P.IconProps>): LucideIcon => {
    const Wrapped = React.forwardRef<SVGSVGElement, P.IconProps>((props, ref) => {
        // Apply duotone weight by default for a branded, premium feel
        return <IconComponent ref={ref} weight="duotone" {...props} />;
    });
    Wrapped.displayName = IconComponent.displayName || "Icon";
    return Wrapped;
};

export const Activity = wrap(P.Pulse);
export const AlertCircle = wrap(P.WarningCircle);
export const AlertTriangle = wrap(P.Warning);
export const ArrowDown = wrap(P.ArrowDown);
export const ArrowDownToLine = wrap(P.ArrowLineDown);
export const ArrowLeft = wrap(P.ArrowLeft);
export const ArrowRight = wrap(P.ArrowRight);
export const ArrowRightLeft = wrap(P.ArrowsLeftRight);
export const ArrowUp = wrap(P.ArrowUp);
export const ArrowUpRight = wrap(P.ArrowUpRight);
export const Award = wrap(P.Trophy);
export const BarChart3 = wrap(P.ChartBar);
export const BookOpen = wrap(P.BookOpen);
export const Building2 = wrap(P.Buildings);
export const Calendar = wrap(P.Calendar);
export const Check = wrap(P.Check);
export const CheckCircle = wrap(P.CheckCircle);
export const CheckCircle2 = wrap(P.CheckCircle);
export const ChevronDown = wrap(P.CaretDown);
export const ChevronLeft = wrap(P.CaretLeft);
export const ChevronRight = wrap(P.CaretRight);
export const ChevronUp = wrap(P.CaretUp);
export const Clock = wrap(P.Clock);
export const Code = wrap(P.Code);
export const Code2 = wrap(P.CodeBlock);
export const Copy = wrap(P.Copy);
export const CreditCard = wrap(P.CreditCard);
export const Crown = wrap(P.Crown);
export const DollarSign = wrap(P.CurrencyDollar);
export const Download = wrap(P.Download);
export const ExternalLink = wrap(P.ArrowSquareOut);
export const Eye = wrap(P.Eye);
export const EyeOff = wrap(P.EyeSlash);
export const FileText = wrap(P.FileText);
export const Globe = wrap(P.Globe);
export const Globe2 = wrap(P.Globe);
export const Heart = wrap(P.Heart);
export const HelpCircle = wrap(P.Question);
export const Home = wrap(P.House);
export const SquaresFour = wrap(P.SquaresFour);
export const Broadcast = wrap(P.Broadcast);
export const Key = wrap(P.Key);
export const KeyRound = wrap(P.Key);
export const Layers = wrap(P.Stack);
export const Link2 = wrap(P.Link);
export const Loader2 = wrap(P.Spinner);
export const Lock = wrap(P.Lock);
export const LockKeyhole = wrap(P.Lock);
export const LogOut = wrap(P.SignOut);
export const Mail = wrap(P.Envelope);
export const MailCheck = wrap(P.Envelope);
export const Menu = wrap(P.List);
export const MessageSquare = wrap(P.Chat);
export const Pause = wrap(P.Pause);
export const Play = wrap(P.Play);
export const PlayCircle = wrap(P.PlayCircle);
export const PlugZap = wrap(P.Plug);
export const Plus = wrap(P.Plus);
export const Power = wrap(P.Power);
export const QrCode = wrap(P.QrCode);
export const ReceiptText = wrap(P.Receipt);
export const RefreshCcw = wrap(P.ArrowCounterClockwise);
export const RefreshCw = wrap(P.ArrowsClockwise);
export const RotateCw = wrap(P.ArrowClockwise);
export const Save = wrap(P.FloppyDisk);
export const Send = wrap(P.PaperPlaneRight);
export const Server = wrap(P.Database);
export const Share2 = wrap(P.ShareNetwork);
export const Shield = wrap(P.Shield);
export const ShieldAlert = wrap(P.ShieldWarning);
export const ShieldCheck = wrap(P.ShieldCheck);
export const ShieldOff = wrap(P.ShieldSlash);
export const ShieldX = wrap(P.ShieldWarning);
export const ShoppingBag = wrap(P.ShoppingBag);
export const Sliders = wrap(P.Sliders);
export const Sparkles = wrap(P.Sparkle);
export const Terminal = wrap(P.Terminal);
export const TimerReset = wrap(P.Timer);
export const Trash2 = wrap(P.Trash);
export const Upload = wrap(P.Upload);
export const User = wrap(P.User);
export const UserPlus = wrap(P.UserPlus);
export const Users = wrap(P.Users);
export const Wallet = wrap(P.Wallet);
export const WalletCards = wrap(P.Cardholder);
export const Webhook = wrap(P.WebhooksLogo);
export const X = wrap(P.X);
export const XCircle = wrap(P.XCircle);
export const Zap = wrap(P.Lightning);
export const Trophy = wrap(P.Trophy);
