"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Bell, X } from "@/components/icons";

/* The notification bell, for both dashboards.
 *
 * WHY IT IS NOT A DM. Platform announcements used to arrive as direct messages, which put
 * "scheduled maintenance on Sunday" in the same thread as correspondence with a merchant and made
 * both harder to read. This reads account_notifications instead — see that table's migration
 * header. Web Push remains a separate, opt-in channel; the bell is the durable one, so an account
 * that never granted browser permission still sees the announcement.
 *
 * PLACEMENT. Rendered beside the dashboard title on desktop and inside the header bar on mobile.
 * Both mount the same component; only the surrounding layout differs, so there is one unread
 * count and one read state rather than two that can disagree.
 *
 * The panel is a plain absolutely-positioned div rather than a portal: it is anchored to the bell,
 * and a portal would need the trigger's position measured and re-measured on scroll for no gain.
 */

type Notification = {
    id: string;
    title: string;
    body: string;
    url: string | null;
    source: string;
    readAt: string | null;
    createdAt: string;
};

/* Coarse on purpose. An announcement's exact minute is never what the reader wants — "2h ago" is,
   and it needs no locale handling or dependency. */
function relativeTime(iso: string): string {
    const then = new Date(iso).getTime();
    if (!Number.isFinite(then)) return "";
    const seconds = Math.max(0, Math.round((Date.now() - then) / 1000));
    if (seconds < 60) return "just now";
    const minutes = Math.round(seconds / 60);
    if (minutes < 60) return `${minutes}m ago`;
    const hours = Math.round(minutes / 60);
    if (hours < 24) return `${hours}h ago`;
    const days = Math.round(hours / 24);
    if (days < 7) return `${days}d ago`;
    return new Date(iso).toLocaleDateString();
}

export default function NotificationBell({
    audience,
    accent,
    className = "",
}: {
    audience: "USER" | "MERCHANT";
    /* Passed rather than hardcoded so each dashboard keeps its own accent: lime for users, teal
       for merchants. Applied through a CSS variable — a class built by interpolation would never
       be generated by Tailwind's source scan. */
    accent: string;
    className?: string;
}) {
    const [open, setOpen] = useState(false);
    const [items, setItems] = useState<Notification[]>([]);
    const [unread, setUnread] = useState(0);
    const [loading, setLoading] = useState(false);
    const [failed, setFailed] = useState(false);
    const containerRef = useRef<HTMLDivElement | null>(null);

    const load = useCallback(async () => {
        setLoading(true);
        try {
            const res = await fetch(`/api/notifications?audience=${audience}`);
            if (!res.ok) throw new Error(String(res.status));
            const data = await res.json();
            setItems(Array.isArray(data.notifications) ? data.notifications : []);
            setUnread(Number(data.unreadCount) || 0);
            setFailed(false);
        } catch {
            /* A bell that cannot load is a silent bell, which is worse than an honest one: the
               reader would assume there is nothing to see. */
            setFailed(true);
        } finally {
            setLoading(false);
        }
    }, [audience]);

    useEffect(() => {
        void load();
    }, [load]);

    /* Close on outside click and on Escape. Both listeners are attached only while open, so a
       closed bell costs nothing. */
    useEffect(() => {
        if (!open) return;
        const onPointerDown = (event: MouseEvent) => {
            if (!containerRef.current?.contains(event.target as Node)) setOpen(false);
        };
        const onKeyDown = (event: KeyboardEvent) => {
            if (event.key === "Escape") setOpen(false);
        };
        document.addEventListener("mousedown", onPointerDown);
        document.addEventListener("keydown", onKeyDown);
        return () => {
            document.removeEventListener("mousedown", onPointerDown);
            document.removeEventListener("keydown", onKeyDown);
        };
    }, [open]);

    const markAllRead = async () => {
        /* Optimistic: the badge clears immediately, because waiting on a round trip to acknowledge
           a click the reader already made feels broken. A failed write is corrected by the reload. */
        const previous = items;
        const previousUnread = unread;
        const now = new Date().toISOString();
        setItems((current) => current.map((item) => ({ ...item, readAt: item.readAt ?? now })));
        setUnread(0);
        try {
            const res = await fetch("/api/notifications", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ audience, all: true }),
            });
            if (!res.ok) throw new Error(String(res.status));
            const data = await res.json();
            setUnread(Number(data.unreadCount) || 0);
        } catch {
            setItems(previous);
            setUnread(previousUnread);
        }
    };

    const openPanel = () => {
        const next = !open;
        setOpen(next);
        /* Refetch on open so a bell left mounted for an hour is not showing an hour-old list. */
        if (next) void load();
    };

    return (
        <div
            ref={containerRef}
            className={`relative ${className}`}
            style={{ "--nb-accent": accent } as React.CSSProperties}
        >
            <button
                type="button"
                onClick={openPanel}
                aria-label={unread > 0 ? `Notifications, ${unread} unread` : "Notifications"}
                aria-expanded={open}
                className="relative grid h-9 w-9 place-items-center rounded-full border border-white/10 bg-white/[0.04] text-white/70 transition-all hover:border-[color:var(--nb-accent)]/30 hover:bg-white/[0.08] hover:text-white"
            >
                <Bell className="h-4 w-4" />
                {unread > 0 && (
                    <span className="absolute -right-0.5 -top-0.5 flex h-4 min-w-4 items-center justify-center rounded-full bg-red-500 px-1 text-[9px] font-bold text-white">
                        {unread > 9 ? "9+" : unread}
                    </span>
                )}
            </button>

            {open && (
                <div
                    role="dialog"
                    aria-label="Notifications"
                    /* Right-aligned so it cannot overflow the viewport when the bell sits near the
                       right edge of a header. */
                    className="absolute right-0 z-50 mt-2 w-[min(22rem,calc(100vw-2rem))] overflow-hidden rounded-2xl border border-white/10 bg-[#0b0b0e] shadow-[0_16px_48px_rgba(0,0,0,0.6)]"
                >
                    <div className="flex items-center justify-between gap-3 border-b border-white/5 px-4 py-3">
                        <p className="text-xs font-bold text-white">Notifications</p>
                        <div className="flex items-center gap-2">
                            {unread > 0 && (
                                <button
                                    type="button"
                                    onClick={markAllRead}
                                    className="text-[10px] font-semibold text-[color:var(--nb-accent)] transition hover:opacity-80"
                                >
                                    Mark all read
                                </button>
                            )}
                            <button
                                type="button"
                                onClick={() => setOpen(false)}
                                aria-label="Close notifications"
                                className="text-white/40 transition-colors hover:text-white"
                            >
                                <X className="h-3.5 w-3.5" />
                            </button>
                        </div>
                    </div>

                    <div className="max-h-[22rem] overflow-y-auto">
                        {loading && items.length === 0 ? (
                            <p className="px-4 py-8 text-center text-xs text-white/40">Loading…</p>
                        ) : failed ? (
                            <div className="px-4 py-8 text-center">
                                <p className="text-xs text-white/50">We couldn&apos;t load your notifications.</p>
                                <button
                                    type="button"
                                    onClick={() => void load()}
                                    className="mt-2 text-[10px] font-semibold text-[color:var(--nb-accent)] transition hover:opacity-80"
                                >
                                    Try again
                                </button>
                            </div>
                        ) : items.length === 0 ? (
                            <div className="px-4 py-10 text-center">
                                <Bell className="mx-auto mb-3 h-7 w-7 text-white/20" />
                                <p className="text-xs text-white/45">Nothing new</p>
                                <p className="mt-1 text-[10px] text-white/30">
                                    Updates from the SubScript team will show up here.
                                </p>
                            </div>
                        ) : (
                            <ul className="divide-y divide-white/5">
                                {items.map((item) => {
                                    const isUnread = !item.readAt;
                                    const content = (
                                        <>
                                            <div className="flex items-start gap-2">
                                                {/* Unread marker, and the only thing distinguishing the
                                                    two states other than title weight. */}
                                                <span
                                                    className={`mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full ${
                                                        isUnread ? "bg-[color:var(--nb-accent)]" : "bg-transparent"
                                                    }`}
                                                />
                                                <div className="min-w-0 flex-1">
                                                    <p className={`text-[11px] leading-snug ${isUnread ? "font-bold text-white" : "font-semibold text-white/70"}`}>
                                                        {item.title}
                                                    </p>
                                                    <p className="mt-0.5 text-[10px] leading-relaxed text-white/50">{item.body}</p>
                                                    <p className="mt-1 text-[9px] text-white/30">{relativeTime(item.createdAt)}</p>
                                                </div>
                                            </div>
                                        </>
                                    );

                                    return (
                                        <li key={item.id} className="px-4 py-3 transition-colors hover:bg-white/[0.03]">
                                            {item.url ? (
                                                <a href={item.url} className="block" onClick={() => setOpen(false)}>
                                                    {content}
                                                </a>
                                            ) : (
                                                content
                                            )}
                                        </li>
                                    );
                                })}
                            </ul>
                        )}
                    </div>
                </div>
            )}
        </div>
    );
}
