"use client";

import Link from "next/link";
import { ArrowLeft, Shield } from "@/components/icons";
import Navbar from "@/components/Navbar";
import AnimatedGradientBg from "@/components/AnimatedGradientBg";

const sections = [
  {
    title: "1. Privacy Principles",
    body: [
      "SubScript is built to reduce Web3 friction while keeping payment state transparent enough to verify. We collect the minimum off-chain data needed to operate accounts, receipts, webhooks, support, and notifications.",
      "Some payment data is written to public blockchains. Public blockchain data is permanent, globally visible, and not fully controlled by SubScript.",
    ],
  },
  {
    title: "2. Account and Wallet Information",
    body: [
      "If you sign up with an external wallet, we may store your wallet address, selected role, account settings, alias, linked email, and notification preferences.",
      "If you sign up with email or Continue with Google, supported wallet providers such as Circle may provision a user-controlled embedded wallet. SubScript may store the resulting wallet address, social login email, Circle user references, and account role. We do not store seed phrases.",
      "If you link an email to a wallet account, that email is used for notifications and account communication. Linking email to a wallet does not by itself mean SubScript can recover an external self-custody wallet.",
    ],
  },
  {
    title: "3. Payment, Receipt, and Memo Data",
    body: [
      "SubScript may store Checkout Intent IDs, payment link IDs, receipt IDs, merchant references, payer references, transaction hashes, memo payloads, payment status, amount, token, timestamp, and webhook delivery status.",
      "Receipt pages are designed to be human-readable. By default, receipt visibility is intended for the payer, merchant, and SubScript. Future invite flows may allow a payer or merchant to share a receipt with selected viewers.",
      "Arc Network memo data and transaction hashes may be public or indexable depending on how the payment is executed.",
    ],
  },
  {
    title: "4. Merchant Data and Webhooks",
    body: [
      "For merchants, we may store API key metadata, webhook endpoints, webhook secrets, DNS aliases, branding, payment links, pricing configuration, and integration settings.",
      "Webhook payloads may include intent IDs, payment IDs, receipt IDs, amount paid, status, and transaction references so merchants can fulfill purchases in their own systems.",
    ],
  },
  {
    title: "5. Cookies and Session Data",
    body: [
      "SubScript uses cookies or similar storage to keep users signed in, preserve dashboard sessions, support embedded wallet login flows, and protect API requests.",
      "Circle wallet session material generated by the frontend SDK is browser-scoped session material. It must not be treated as a global deployment secret and must not be shared across users.",
    ],
  },
  {
    title: "6. Emails and Notifications",
    body: [
      "If you provide an email, we may use it for account notifications, sign-up messages, payment receipts, failed payment alerts, subscription notices, product updates, security messages, and support.",
      "We may use email delivery providers to send these messages. Those providers process message metadata needed to deliver email.",
    ],
  },
  {
    title: "7. Analytics, Security, and Logs",
    body: [
      "We may process limited technical data such as IP-derived region, device/browser information, request timestamps, rate-limit events, errors, and security logs to protect the service and improve reliability.",
      "We do not sell personal information. We do not use private payment receipt data for advertising profiles.",
    ],
  },
  {
    title: "8. Your Choices and Deletion Limits",
    body: [
      "You may request access, correction, export, or deletion of off-chain account data by contacting SubScript. We may retain records needed for security, legal, fraud prevention, or financial audit purposes.",
      "We cannot delete or alter public blockchain records, third-party explorer records, or transaction data already propagated across decentralized networks.",
    ],
  },
  {
    title: "9. Contact",
    body: [
      "For privacy requests, email compliance@subscriptonarc.com. Include the email or wallet address connected to the request so we can locate the relevant account records.",
    ],
  },
];

export default function PrivacyPolicy() {
  return (
    <main className="relative min-h-screen w-full max-w-[100vw] overflow-x-hidden bg-transparent text-white selection:bg-[#00d2b4]/30 selection:text-white">
      <AnimatedGradientBg />
      <div className="relative z-10">
        <Navbar />

        <div className="mx-auto max-w-4xl px-6 pb-24 pt-36 sm:px-8">
          <Link href="/" className="mb-8 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-white/50 transition-colors hover:text-white">
            <ArrowLeft className="h-3.5 w-3.5" />
            Back to Home
          </Link>

          <div className="mb-12">
            <span className="mb-3 block text-xs font-semibold uppercase tracking-[0.2em] text-white/40">
              Protocol Privacy
            </span>
            <h1 className="flex items-center gap-3 text-4xl font-extrabold uppercase leading-none tracking-tight text-white sm:text-5xl">
              Privacy <span className="font-serif font-normal italic lowercase tracking-normal text-[#00d2b4]">policy</span>
            </h1>
            <p className="mt-4 font-mono text-xs text-white/40">Last Updated: June 20th, 2026</p>
          </div>

          <div className="liquid-glass space-y-8 rounded-[32px] border border-white/5 p-8 text-sm leading-relaxed text-white/70 md:p-10">
            {sections.map((section, index) => (
              <section key={section.title} className="space-y-3">
                <div className="flex items-center gap-2">
                  {index === 0 && <Shield className="h-4 w-4 text-[#00d2b4]" />}
                  <h2 className="text-base font-bold uppercase tracking-wider text-white">{section.title}</h2>
                </div>
                {section.body.map((paragraph) => (
                  <p key={paragraph}>{paragraph}</p>
                ))}
              </section>
            ))}
          </div>
        </div>

        <footer className="border-t border-white/5 bg-[#111111]/30 py-12">
          <div className="mx-auto flex max-w-4xl flex-col items-center justify-between gap-4 px-6 text-[10px] text-white/40 sm:flex-row">
            <span>© 2026 SubScript Protocol. All rights reserved.</span>
            <div className="flex gap-4">
              <Link href="/terms" className="transition hover:text-white">Terms of Service</Link>
              <Link href="/privacy" className="transition hover:text-white">Privacy Policy</Link>
            </div>
          </div>
        </footer>
      </div>
    </main>
  );
}
