import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireScope } from "@/lib/admin/guard";
import { ADMIN_ACTIONS, isAdminAction } from "@/lib/admin/audit";
import { jsonOk } from "@/lib/http/json";

/* The read path for admin_audit_log.
 *
 * GET /api/admin/audit-log?actor=&action=&target=&from=&to=&cursor=&limit=
 *
 * recordAdminAction has been writing rows for a long time; until this route nothing read them
 * back. An append-only log nobody can query deters nothing and answers nothing — during an
 * incident "who turned this off, and what was it before" is the whole point of having kept the
 * before-value, and that answer was sitting in a table with no way in.
 *
 * WHY THE `compliance` SCOPE AND NOT ANY ADMIN. This gate used to be bare requireAdmin, and the
 * reasoning written here was sound at the time: every admin could already read every user record
 * through the rest of this console, so gating the log more tightly than the data it describes
 * would have been theatre. Scoped admins broke that premise — a `read` or `support` admin no
 * longer sees the data this log describes, and the log spans every scope at once, naming who
 * banned whom and which KYC decisions were overridden. Reading it is an oversight function, so it
 * sits with compliance. Root holds every scope and is unaffected.
 *
 * Still NOT requireRootAdmin: the log is append-only, with no update or delete path anywhere in
 * the codebase, so a reader cannot tamper with what it reads. Consistent with the rest of
 * /api/admin, where only the dangerous WRITES are root-gated (see requireRootAdmin).
 *
 * THIS READ IS DELIBERATELY NOT AUDIT-LOGGED. Every load of the console tab would append a row,
 * and the log would fill with the act of reading the log — burying the actions an auditor opened
 * it to find under noise generated by looking. The omission is a decision, not an oversight.
 */

/* Matches the `gen_random_uuid()` default on the id column. Checked before the query so a
 * hand-mangled ?cursor= comes back as a 400 instead of a Prisma error surfacing as a 500. An id we
 * ourselves handed out will always still resolve — the table is append-only, so no row a previous
 * page pointed at can have gone away. */
const CURSOR_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/* Bare calendar dates ("2026-08-21") parse to midnight UTC. Left alone, `to` would then exclude
 * every row from the day the operator actually named, and asking for "up to today" would return
 * nothing at all. A date with no time means the whole day. */
const DATE_ONLY_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

const DEFAULT_LIMIT = 50;
const MAX_LIMIT = 200;

function parseBoundary(raw: string, endOfDay: boolean): Date | null {
    const parsed = new Date(raw);
    if (Number.isNaN(parsed.getTime())) return null;
    if (endOfDay && DATE_ONLY_PATTERN.test(raw)) {
        parsed.setUTCHours(23, 59, 59, 999);
    }
    return parsed;
}

export async function GET(request: Request) {
    const auth = await requireScope(request, "compliance");
    if (!auth.ok) return auth.response;

    try {
        const { searchParams } = new URL(request.url);

        /* Both columns are written lowercased by recordAdminAction, so lowercasing the input is
           enough — Prisma's `mode: "insensitive"` would force a citext-style scan and throw away
           the [actor, createdAt desc] and [target, createdAt desc] indexes for no gain. */
        const actor = searchParams.get("actor")?.trim().toLowerCase() || null;
        const target = searchParams.get("target")?.trim().toLowerCase() || null;
        const action = searchParams.get("action")?.trim() || null;
        const cursor = searchParams.get("cursor")?.trim() || null;
        const from = searchParams.get("from")?.trim() || null;
        const to = searchParams.get("to")?.trim() || null;

        /* Reject an unknown action rather than ignoring the filter. Dropping it would answer a
           narrow question with the entire log, and the caller has no way to tell the difference
           between "no rows matched" and "your filter was never applied". */
        if (action && !isAdminAction(action)) {
            return NextResponse.json(
                { error: `Unknown action "${action}". Pick one from the actions list on this response.` },
                { status: 400 },
            );
        }

        if (cursor && !CURSOR_PATTERN.test(cursor)) {
            return NextResponse.json({ error: "cursor must be an id from a previous page." }, { status: 400 });
        }

        const fromDate = from ? parseBoundary(from, false) : null;
        if (from && !fromDate) {
            return NextResponse.json({ error: "from must be an ISO date or timestamp." }, { status: 400 });
        }
        const toDate = to ? parseBoundary(to, true) : null;
        if (to && !toDate) {
            return NextResponse.json({ error: "to must be an ISO date or timestamp." }, { status: 400 });
        }
        /* An inverted range can only match nothing. Saying so beats an empty table the operator
           reads as "no admin has touched this", which is the opposite of the truth. */
        if (fromDate && toDate && fromDate > toDate) {
            return NextResponse.json({ error: "from must come before to." }, { status: 400 });
        }

        const limitParam = searchParams.get("limit");
        const limit = Math.min(Math.max(1, Number(limitParam) || DEFAULT_LIMIT), MAX_LIMIT);

        const where: Record<string, unknown> = {};
        /* Exact on actor (an admin wallet is pasted whole, and a substring match across actors
           would quietly widen "what did this admin do"); contains on target, because an admin
           chasing an incident pastes the last few characters of an address off a screen.
           Worth knowing: exact actor rides [actor, createdAt desc], but an unanchored LIKE cannot
           use [target, createdAt desc] — a target-only search leans on the createdAt index and the
           limit to stay bounded. Pair it with a date range on a log that has grown large. */
        if (actor) where.actor = actor;
        if (action) where.action = action;
        if (target) where.target = { contains: target };
        if (fromDate || toDate) {
            where.createdAt = {
                ...(fromDate ? { gte: fromDate } : {}),
                ...(toDate ? { lte: toDate } : {}),
            };
        }

        /* id breaks the tie on createdAt. Two actions inside the same clock tick — a flag toggle
           that writes several rows in one request — would otherwise come back in an unstable order,
           and a cursor page can silently skip or repeat a row when the sort is not total. */
        const rows = await prisma.adminAuditLog.findMany({
            where,
            orderBy: [{ createdAt: "desc" }, { id: "desc" }],
            take: limit + 1,
            ...(cursor ? { cursor: { id: cursor }, skip: 1 } : {}),
            select: {
                id: true,
                actor: true,
                action: true,
                target: true,
                detail: true,
                ip: true,
                createdAt: true,
            },
        });

        /* Over-fetch by one to learn whether another page exists, then hand back only `limit`. The
           spare row is the answer to "is there more", so it is never serialized. */
        const hasMore = rows.length > limit;
        const page = hasMore ? rows.slice(0, limit) : rows;

        return jsonOk({
            rows: page.map((row) => ({
                id: row.id,
                actor: row.actor,
                action: row.action,
                target: row.target,
                detail: row.detail ?? null,
                ip: row.ip,
                createdAt: row.createdAt.toISOString(),
            })),
            nextCursor: hasMore ? page[page.length - 1].id : null,
            /* The whole taxonomy, not just the actions present in this page — a filter built from
               the rows on screen can never find the action you are missing. Sorted so the dropdown
               order does not change when a new action is appended in @/lib/admin/audit. */
            actions: [...ADMIN_ACTIONS].sort(),
        });
    } catch (error) {
        console.error("[admin/audit-log] read failed:", error);
        return NextResponse.json({ error: "Failed to load the audit log" }, { status: 500 });
    }
}
