-- Money-level admin controls: disputes, refunds, manual adjustments, fee overrides,
-- payout-address locks, merchant signup suspension, and treasury wallet registry.
--
-- WHY THIS MIGRATION EXISTS
-- -------------------------
-- Finding 4 of docs/admin-capabilities-audit.md. "No chargebacks" is a real advantage of paying
-- in stablecoin, and it was being carried as if it also meant "no disputes" — so when a merchant
-- genuinely takes money and delivers nothing, staff had exactly one lever: ban the merchant.
-- That protects the next customer and does nothing for the one who already paid. Section 2.2 was
-- eight ❌ in a row, and every one of them is a question a first serious merchant asks.
--
-- THE CENTRAL CONSTRAINT: SUBSCRIPT DOES NOT HOLD CUSTOMER FUNDS
-- ------------------------------------------------------------
-- Payments settle wallet-to-wallet on Arc. There is no platform float to refund out of, and an
-- on-chain transfer cannot be reversed by anyone, including us. So a "refund" here is one of
-- three genuinely different things, and conflating them would be the worst possible design:
--
--   MERCHANT_BALANCE  — deduct from merchants.available_balance_usdc and pay the customer from
--                       the merchant's undrawn settlement. Actually reverses value. Only works
--                       while the merchant still has an undrawn balance, which is why the route
--                       checks it and why status carries INSUFFICIENT_FUNDS.
--   VAULT_ESCROW      — return unspent commit escrow from a metered vault. The cleanest case:
--                       the money never left escrow, so this is a book entry plus a withdrawal.
--   OFF_PLATFORM      — the merchant refunds directly and staff record it. No money moves here
--                       at all. Recorded anyway, because the dispute has to close with an
--                       outcome and "merchant says they sent it" is evidence, not a resolution.
--
-- A single `refunds` table with a nullable tx_hash and a hopeful status would have let an
-- operator believe money moved when it did not. `method` is NOT NULL for that reason.
--
-- WHY DISPUTES AND REFUNDS ARE SEPARATE TABLES
-- -------------------------------------------
-- A dispute is a claim with a lifecycle and possibly no refund at the end (rejected, withdrawn,
-- resolved by the merchant shipping the goods). A refund is a money movement that may exist with
-- no dispute (a merchant asking us to return an overcharge). One table would force every refund
-- to invent a dispute and every rejected dispute to carry a zero refund.
--
-- Note MerchantReport already exists for user-filed scam reports against commit merchants. That
-- is intake, like merchant_access_requests: it records that someone complained. A dispute is the
-- case staff open in response, which may cover several reports. The dispute row links back.
--
-- DUAL CONTROL IS ENFORCED IN SQL, NOT ONLY IN THE ROUTE
-- ----------------------------------------------------
-- Every row that moves money carries approved_by with a CHECK that it differs from created_by,
-- and the executing code refuses to act on an unapproved row. Section 3 of the audit calls out
-- dual control on irreversible actions as the missing wrapper around every power; a refund and a
-- manual credit are the two most irreversible things in the console.
--
-- All statements idempotent, one transaction, RLS deny-all.

-- ---------------------------------------------------------------------------
-- 1. Disputes
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.platform_disputes (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Human-facing case number, so support can say it aloud on a call. Generated by the route.
    case_number       TEXT NOT NULL UNIQUE,
    -- Who is out of pocket, and who they are disputing with. Both lowercased.
    customer_address  TEXT NOT NULL,
    merchant_address  TEXT NOT NULL,
    -- What the dispute is about. Exactly one of these is normally set; all are nullable because
    -- a dispute can be opened from a complaint that names none of them precisely yet.
    tx_hash           TEXT,
    receipt_id        TEXT,
    subscription_id   BIGINT,
    -- The PSA that minted subscription_id. Meaningless without it — see the note on
    -- subscriptions.contract_address about redeploys restarting ids at 1.
    contract_address  TEXT,
    vault_id          UUID,
    -- The user-filed report that triggered this case, when there was one.
    merchant_report_id UUID,
    amount_usdc       BIGINT NOT NULL,
    -- 'NOT_DELIVERED' | 'NOT_AS_DESCRIBED' | 'UNAUTHORIZED' | 'DUPLICATE' | 'OVERCHARGE'
    -- | 'SUBSCRIPTION_NOT_CANCELLED' | 'OTHER'. Validated in code.
    reason_code       TEXT NOT NULL,
    detail            TEXT,
    -- 'OPEN' | 'MERCHANT_RESPONDED' | 'RESOLVED_REFUNDED' | 'RESOLVED_PARTIAL'
    -- | 'RESOLVED_MERCHANT_FAVOUR' | 'WITHDRAWN' | 'EXPIRED'
    status            TEXT NOT NULL DEFAULT 'OPEN',
    -- 'CUSTOMER' | 'ADMIN' | 'MERCHANT' — who opened the case. A dispute a merchant raises
    -- against their own charge (an overcharge they spotted) reviews differently from one a
    -- customer raises against them.
    opened_by_kind    TEXT NOT NULL DEFAULT 'ADMIN',
    opened_by         TEXT NOT NULL,
    -- Deadline for the merchant to respond. Drives the queue's aging view; a dispute with no
    -- clock is a dispute nobody works.
    merchant_due_at   TIMESTAMPTZ,
    merchant_response TEXT,
    merchant_responded_at TIMESTAMPTZ,
    resolution_note   TEXT,
    resolved_by       TEXT,
    resolved_at       TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT platform_disputes_amount_positive CHECK (amount_usdc > 0)
);

-- The queue read, and the two per-party reads the console and any future merchant-facing view
-- both need.
CREATE INDEX IF NOT EXISTS idx_platform_disputes_queue
    ON public.platform_disputes (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_platform_disputes_merchant
    ON public.platform_disputes (merchant_address, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_platform_disputes_customer
    ON public.platform_disputes (customer_address, created_at DESC);
-- Dispute-rate-per-merchant (§1.3) is a count over this, so the merchant index above carries it.

-- One live dispute per transaction. Two open cases over one payment produce two refunds.
CREATE UNIQUE INDEX IF NOT EXISTS uq_platform_disputes_live_tx
    ON public.platform_disputes (lower(tx_hash))
    WHERE tx_hash IS NOT NULL
      AND status IN ('OPEN', 'MERCHANT_RESPONDED');

ALTER TABLE public.platform_disputes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deny all public access on platform_disputes" ON public.platform_disputes;
CREATE POLICY "Deny all public access on platform_disputes" ON public.platform_disputes FOR ALL USING (false);

-- ---------------------------------------------------------------------------
-- 2. Refunds
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.platform_refunds (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    dispute_id       UUID REFERENCES public.platform_disputes(id) ON DELETE SET NULL,
    customer_address TEXT NOT NULL,
    merchant_address TEXT NOT NULL,
    -- The payment being refunded, when one is identified.
    tx_hash          TEXT,
    receipt_id       TEXT,
    vault_id         UUID,
    amount_usdc      BIGINT NOT NULL,
    -- NOT NULL on purpose. See the three-methods note in the header: a refund whose method is
    -- unknown is a refund whose money may not have moved.
    -- 'MERCHANT_BALANCE' | 'VAULT_ESCROW' | 'OFF_PLATFORM'
    method           TEXT NOT NULL CHECK (method IN ('MERCHANT_BALANCE', 'VAULT_ESCROW', 'OFF_PLATFORM')),
    -- 'PENDING_APPROVAL' | 'APPROVED' | 'PROCESSING' | 'COMPLETED' | 'FAILED'
    -- | 'INSUFFICIENT_FUNDS' | 'REJECTED' | 'CANCELLED'
    status           TEXT NOT NULL DEFAULT 'PENDING_APPROVAL',
    reason           TEXT NOT NULL,
    created_by       TEXT NOT NULL,
    -- Dual control. NULL until a second admin approves; the executor refuses to run without it.
    approved_by      TEXT,
    approved_at      TIMESTAMPTZ,
    rejected_by      TEXT,
    rejected_at      TIMESTAMPTZ,
    -- Set for MERCHANT_BALANCE and VAULT_ESCROW once the payout is broadcast. Stays NULL for
    -- OFF_PLATFORM, where no chain movement is ours to record.
    payout_tx_hash   TEXT,
    -- Operator-supplied evidence for OFF_PLATFORM (the merchant's own transfer hash, an email).
    external_evidence TEXT,
    last_error       TEXT,
    completed_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT platform_refunds_amount_positive CHECK (amount_usdc > 0),
    -- The control the whole design rests on. Enforced here as well as in the route because a
    -- route is one refactor away from losing it and this one cannot be undone.
    CONSTRAINT platform_refunds_no_self_approval
        CHECK (approved_by IS NULL OR lower(approved_by) <> lower(created_by))
);

CREATE INDEX IF NOT EXISTS idx_platform_refunds_status
    ON public.platform_refunds (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_platform_refunds_merchant
    ON public.platform_refunds (merchant_address, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_platform_refunds_customer
    ON public.platform_refunds (customer_address, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_platform_refunds_dispute
    ON public.platform_refunds (dispute_id);

-- One live refund per transaction, so a double-click or a retried approval cannot pay twice.
CREATE UNIQUE INDEX IF NOT EXISTS uq_platform_refunds_live_tx
    ON public.platform_refunds (lower(tx_hash))
    WHERE tx_hash IS NOT NULL
      AND status IN ('PENDING_APPROVAL', 'APPROVED', 'PROCESSING', 'COMPLETED');

ALTER TABLE public.platform_refunds ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deny all public access on platform_refunds" ON public.platform_refunds;
CREATE POLICY "Deny all public access on platform_refunds" ON public.platform_refunds FOR ALL USING (false);

-- ---------------------------------------------------------------------------
-- 3. Manual balance adjustments
-- ---------------------------------------------------------------------------
-- Credits and debits against merchants.available_balance_usdc, for the cases a refund does not
-- describe: goodwill after an outage, correcting a double-charged fee, clawing back a
-- mistakenly-credited settlement. Append-only: a wrong adjustment is corrected by an opposite
-- adjustment, never by editing the row, so the balance's history stays reconstructible.

CREATE TABLE IF NOT EXISTS public.balance_adjustments (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Lowercased merchant wallet. Only merchant balances are adjustable: customer funds live in
    -- the customer's own wallet or in vault escrow, neither of which the platform can credit.
    address       TEXT NOT NULL,
    -- 'CREDIT' (increase available balance) | 'DEBIT' (decrease it)
    direction     TEXT NOT NULL CHECK (direction IN ('CREDIT', 'DEBIT')),
    amount_usdc   BIGINT NOT NULL,
    -- 'GOODWILL' | 'FEE_CORRECTION' | 'SETTLEMENT_CORRECTION' | 'DISPUTE_RESOLUTION'
    -- | 'CLAWBACK' | 'OTHER'
    category      TEXT NOT NULL,
    reason        TEXT NOT NULL,
    -- Balance either side of the write, captured inside the same transaction as the update. An
    -- adjustment ledger whose rows cannot be reconciled against the balance they claim to
    -- explain is decoration.
    balance_before BIGINT NOT NULL,
    balance_after  BIGINT NOT NULL,
    reference_type TEXT,
    reference_id   TEXT,
    created_by    TEXT NOT NULL,
    approved_by   TEXT,
    approved_at   TIMESTAMPTZ,
    -- 'PENDING_APPROVAL' | 'APPLIED' | 'REJECTED'
    status        TEXT NOT NULL DEFAULT 'PENDING_APPROVAL',
    applied_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT balance_adjustments_amount_positive CHECK (amount_usdc > 0),
    CONSTRAINT balance_adjustments_no_self_approval
        CHECK (approved_by IS NULL OR lower(approved_by) <> lower(created_by))
);

CREATE INDEX IF NOT EXISTS idx_balance_adjustments_address
    ON public.balance_adjustments (address, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_balance_adjustments_status
    ON public.balance_adjustments (status, created_at DESC);

ALTER TABLE public.balance_adjustments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deny all public access on balance_adjustments" ON public.balance_adjustments;
CREATE POLICY "Deny all public access on balance_adjustments" ON public.balance_adjustments FOR ALL USING (false);

-- ---------------------------------------------------------------------------
-- 4. Per-merchant fee override
-- ---------------------------------------------------------------------------
-- SUBSCRIPT_PROTOCOL_FEE_BPS is a compile-time constant, so the 1% was the same for a launch
-- partner, a high-volume merchant, and an account under investigation. One row per merchant,
-- read through getMerchantFeeBps() so a missing row means the constant.

CREATE TABLE IF NOT EXISTS public.merchant_fee_overrides (
    merchant_address TEXT PRIMARY KEY,
    -- Basis points. 0 is legitimate (a waived fee for a launch partner), which is why the CHECK
    -- allows it and why the reader must distinguish "0" from "no row".
    fee_bps          INTEGER NOT NULL,
    reason           TEXT NOT NULL,
    set_by           TEXT NOT NULL,
    -- NULL = until changed. A promotional rate with no expiry becomes permanent by accident.
    expires_at       TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Ceiling at 10%. An override is for discounts and for pricing experiments, not a lever to
    -- quietly take a third of a merchant's revenue.
    CONSTRAINT merchant_fee_overrides_bps_range CHECK (fee_bps >= 0 AND fee_bps <= 1000)
);

ALTER TABLE public.merchant_fee_overrides ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deny all public access on merchant_fee_overrides" ON public.merchant_fee_overrides;
CREATE POLICY "Deny all public access on merchant_fee_overrides" ON public.merchant_fee_overrides FOR ALL USING (false);

-- ---------------------------------------------------------------------------
-- 5. Payout-address locks and merchant signup suspension
-- ---------------------------------------------------------------------------
-- Two merchant-level freezes that stop short of revoking access.
--
-- A payout-address lock is the classic account-takeover control: the single highest-value edit
-- an attacker makes after phishing a merchant is repointing settlement at their own wallet, and
-- merchants.payout_destination had no gate at all.
--
-- A signup suspension stops NEW subscribers while existing subscriptions keep billing — the
-- proportionate response to a merchant selling something questionable, since cutting existing
-- subscriptions punishes their customers for the merchant's behaviour.

CREATE TABLE IF NOT EXISTS public.merchant_payout_locks (
    merchant_address TEXT PRIMARY KEY,
    reason           TEXT NOT NULL,
    locked_by        TEXT NOT NULL,
    expires_at       TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.merchant_payout_locks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deny all public access on merchant_payout_locks" ON public.merchant_payout_locks;
CREATE POLICY "Deny all public access on merchant_payout_locks" ON public.merchant_payout_locks FOR ALL USING (false);

CREATE TABLE IF NOT EXISTS public.merchant_signup_suspensions (
    merchant_address TEXT PRIMARY KEY,
    reason           TEXT NOT NULL,
    -- Shown to a would-be subscriber instead of the checkout. Kept separate from `reason`, which
    -- is internal: "suspected fraud, ticket 412" must not reach a customer.
    public_message   TEXT,
    suspended_by     TEXT NOT NULL,
    expires_at       TIMESTAMPTZ,
    lifted_at        TIMESTAMPTZ,
    lifted_by        TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.merchant_signup_suspensions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deny all public access on merchant_signup_suspensions" ON public.merchant_signup_suspensions;
CREATE POLICY "Deny all public access on merchant_signup_suspensions" ON public.merchant_signup_suspensions FOR ALL USING (false);

-- ---------------------------------------------------------------------------
-- 6. Treasury and hot-wallet registry
-- ---------------------------------------------------------------------------
-- §1.1 exposed exactly one wallet to admins: the gas sponsor, because getSponsorWalletStatus
-- happened to compute it. Every other wallet the platform depends on — the fee collector, the
-- keeper relayer, a cold treasury — was invisible, so "are we solvent" was a question answered
-- by opening a block explorer. Registered here and balance-read live; balances are deliberately
-- NOT stored, only sampled, because a cached balance is a number an operator will trust after
-- it stops being true.

CREATE TABLE IF NOT EXISTS public.treasury_wallets (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    label        TEXT NOT NULL,
    address      TEXT NOT NULL,
    chain_id     INTEGER NOT NULL,
    -- 'SPONSOR' | 'FEE_COLLECTOR' | 'KEEPER' | 'TREASURY' | 'COLD' | 'OTHER'
    kind         TEXT NOT NULL,
    -- Alert when the native or USDC balance drops below this (micro-USDC / wei as appropriate
    -- for `kind`). NULL = no alert, for wallets that are supposed to be empty.
    low_balance_threshold BIGINT,
    note         TEXT,
    active       BOOLEAN NOT NULL DEFAULT true,
    added_by     TEXT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (address, chain_id)
);

CREATE INDEX IF NOT EXISTS idx_treasury_wallets_active
    ON public.treasury_wallets (active, kind);

ALTER TABLE public.treasury_wallets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Deny all public access on treasury_wallets" ON public.treasury_wallets;
CREATE POLICY "Deny all public access on treasury_wallets" ON public.treasury_wallets FOR ALL USING (false);
